### ISSUE TITLE
How to get only Precision and Recall Value?

### ISSUE THREAD

**Issue by benn94** [cguindel/eval_kitti#2]
As the question said, I am just working on getting only precision and recall value?
the map and maos from the 41 by 4 matrix is not in my interest.

**Comment by cguindel** [comment]
I am sorry, but I do not really understand what you are trying to do. Are you trying to compute a single value for precision and another one for recall? Since you are not interested in the AP stat, you would need to choose a threshold value for the detection score and compute the confusion matrix after filtering out the detections below that threshold. Then you would have a fixed point in the precision-recall curves and therefore a single precision-recall pair. However, this script is not suitable to compute those stats in its current state, primarily because it is not standard practice in the literature. Please let me know if that is what you are asking about.

**Comment by cguindel** [comment]
Closed due to inactivity
